"""Static web export filesystem and asset-rewriting helpers."""

from __future__ import annotations

import hashlib
import html as html_lib
import os
import re
import shutil
from pathlib import Path
from urllib.parse import unquote, urlparse

from PIL import Image, UnidentifiedImageError

from papercrown.project import themes
from papercrown.project.manifest import slugify
from papercrown.project.recipe import BookConfig
from papercrown.project.resources import (
    ASSETS_DIR,
    CORE_CSS_FILES,
    CORE_STYLES_DIR,
    FONTS_DIR,
)

# Image extensions copied into static web exports.
WEB_IMAGE_SUFFIXES: set[str] = {
    ".apng",
    ".avif",
    ".gif",
    ".jpeg",
    ".jpg",
    ".png",
    ".svg",
    ".webp",
}
# Matches HTML src/href attributes so their asset paths can be rebased.
_WEB_ASSET_ATTR_RE = re.compile(
    r'(?P<prefix>\b(?:src|href)=["\'])(?P<value>[^"\']+)(?P<suffix>["\'])',
    re.IGNORECASE,
)
# Detects Windows absolute paths before converting them to web output paths.
_WINDOWS_ABSOLUTE_RE = re.compile(r"^[A-Za-z]:[\\/]")
# Matches CSS url(...) references so copied stylesheets can be rebased.
_CSS_URL_RE = re.compile(r"url\(\s*(?P<quote>['\"]?)(?P<value>[^'\")]+)(?P=quote)\s*\)")
# Matches image tags for web-only accessibility and loading attributes.
_IMG_TAG_RE = re.compile(
    r"<img\b(?P<attrs>[^<>]*?)(?P<slash>/?)>",
    re.IGNORECASE | re.DOTALL,
)
_HTML_ATTR_RE = re.compile(
    r"""
    (?P<name>[^\s=/>]+)
    (?:
        \s*=\s*
        (?:
            "(?P<double>[^"]*)"
            |'(?P<single>[^']*)'
            |(?P<bare>[^\s"'=<>`]+)
        )
    )?
    """,
    re.VERBOSE | re.DOTALL,
)
_HASH_SUFFIX_RE = re.compile(r"-(?:[0-9a-f]{10}|[0-9a-f]{12})$", re.IGNORECASE)
_DIMENSION_IMAGE_SUFFIXES = WEB_IMAGE_SUFFIXES - {".svg"}
_DECORATIVE_IMAGE_CLASSES = {
    "chapter-art",
    "cover-art",
    "cover-back-art",
    "section-divider-art",
    "section-divider-frame-art",
    "splash-img",
    "splash-page-art",
}
_DECORATIVE_CONTAINER_RE = re.compile(
    r"<(?:div|figure|section)\b[^>]*\bclass=[\"'][^\"']*"
    r"(?:chapter-art-wrap|cover-art-wrap|ornament-tailpiece|section-divider-art-wrap|"
    r"splash-art|splash-page)"
    r"[^\"']*[\"'][^>]*>\s*(?:<p>\s*)?$",
    re.IGNORECASE | re.DOTALL,
)
_DECORATIVE_IMAGE_PREFIXES = (
    "cover-",
    "divider-",
    "filler-",
    "header-",
    "ornament-",
    "page-finish-",
    "surface-",
    "wear-",
)
_ALT_PREFIX_LABELS = (
    ("diagram", "Diagram"),
    ("faction", "Faction art"),
    ("frame", "Frame art"),
    ("gear", "Gear art"),
    ("power-header", "Power art"),
    ("power-icon", "Power icon"),
    ("spot-class", "Class art"),
    ("spot", "Illustration"),
    ("vista", "Scene"),
    ("class", "Class art"),
)


def reset_web_output(web_root: Path) -> None:
    """Delete and recreate the static web output directory."""
    if web_root.exists():
        shutil.rmtree(web_root)
    web_root.mkdir(parents=True, exist_ok=True)


def copy_web_static_assets(web_root: Path, *, recipe: BookConfig) -> None:
    """Copy stylesheets and bundled fonts into a static web output tree."""
    styles_dir = web_root / "styles"
    styles_dir.mkdir(parents=True, exist_ok=True)
    shutil.copytree(CORE_STYLES_DIR, styles_dir / "core", dirs_exist_ok=True)

    theme = themes.load_theme(recipe)
    theme_out = styles_dir / "themes" / theme.name
    shutil.copytree(theme.root, theme_out, dirs_exist_ok=True)
    write_web_stylesheet_bundle(styles_dir, theme=theme, theme_out=theme_out)

    fonts_out = web_root / "assets" / "fonts"
    fonts_out.mkdir(parents=True, exist_ok=True)
    if FONTS_DIR.is_dir():
        for font in sorted(FONTS_DIR.iterdir(), key=lambda path: path.name):
            if font.is_file():
                shutil.copy2(font, fonts_out / font.name)


def write_web_stylesheet_bundle(
    styles_dir: Path,
    *,
    theme: themes.ThemePack,
    theme_out: Path,
) -> None:
    """Write a generated web CSS bundle from core modules and theme CSS."""
    out = styles_dir / "book.css"
    sources = [styles_dir / "core" / path.name for path in CORE_CSS_FILES]
    sources.extend(theme_out / path.relative_to(theme.root) for path in theme.css_files)
    sections = ["/* Generated by Paper Crown. Edit source CSS, not this file. */"]
    for source in sources:
        label = source.relative_to(styles_dir).as_posix()
        css = rebase_css_urls_for_output(
            source.read_text(encoding="utf-8"),
            source_css=source,
            output_css=out,
        ).strip()
        sections.append(f"/* --- {label} --- */\n{css}")
    out.write_text("\n\n".join(sections) + "\n", encoding="utf-8")


def rebase_css_urls_for_output(
    css: str,
    *,
    source_css: Path,
    output_css: Path,
) -> str:
    """Rebase relative ``url(...)`` references for a generated CSS bundle."""

    def replace(match: re.Match[str]) -> str:
        value = match.group("value").strip()
        if is_external_css_url(value):
            return match.group(0)
        target = (source_css.parent / value).resolve()
        rel = os.path.relpath(target, output_css.parent.resolve()).replace("\\", "/")
        return f"url('{rel}')"

    return _CSS_URL_RE.sub(replace, css)


def is_external_css_url(value: str) -> bool:
    """Return whether a CSS URL should not be rebased."""
    lowered = value.lower()
    return (
        not value
        or lowered.startswith(("data:", "http:", "https:", "file:", "var("))
        or value.startswith(("/", "#"))
    )


def rewrite_web_asset_refs(
    html: str,
    *,
    web_root: Path,
    search_roots: list[Path] | None = None,
) -> str:
    """Copy local image references into ``web_root`` and rewrite HTML attrs."""
    copied: dict[Path, str] = {}
    roots = search_roots or []

    def replace(match: re.Match[str]) -> str:
        value = match.group("value")
        source = local_asset_path(value, search_roots=roots)
        if source is None:
            return match.group(0)
        if source.suffix.lower() not in WEB_IMAGE_SUFFIXES or not source.is_file():
            return match.group(0)
        relative = copy_web_image(source, web_root=web_root, copied=copied)
        return f"{match.group('prefix')}{relative}{match.group('suffix')}"

    return _WEB_ASSET_ATTR_RE.sub(replace, html)


def enhance_web_image_tags(html: str, *, web_root: Path) -> str:
    """Add web-only image attributes after assets have been copied locally."""

    def replace(match: re.Match[str]) -> str:
        attrs = _parse_img_attrs(match.group("attrs"))
        src = _attr_value(attrs, "src")

        if _attr_value(attrs, "loading") is None:
            _set_attr(attrs, "loading", "lazy")
        if _attr_value(attrs, "decoding") is None:
            _set_attr(attrs, "decoding", "async")

        if src:
            dimensions = _web_image_dimensions(src, web_root=web_root)
            if dimensions is not None:
                width, height = dimensions
                if _attr_value(attrs, "width") is None:
                    _set_attr(attrs, "width", str(width))
                if _attr_value(attrs, "height") is None:
                    _set_attr(attrs, "height", str(height))

        alt = _attr_value(attrs, "alt")
        if alt is None or alt == "":
            decorative = _has_decorative_image_context(html, match.start())
            _set_attr(
                attrs,
                "alt",
                (
                    ""
                    if decorative or _is_decorative_web_image(attrs, src)
                    else _alt_text_from_src(src)
                ),
            )

        slash = " /" if match.group("slash") else ""
        return f"<img{_format_img_attrs(attrs)}{slash}>"

    return _IMG_TAG_RE.sub(replace, html)


def local_asset_path(
    value: str,
    *,
    search_roots: list[Path] | None = None,
) -> Path | None:
    """Resolve a local HTML asset reference to a filesystem path if possible."""
    if is_non_file_reference(value):
        return None

    path_value = value.split("#", 1)[0].split("?", 1)[0]
    if not path_value:
        return None

    unquoted = unquote(path_value)
    if _WINDOWS_ABSOLUTE_RE.match(unquoted):
        return Path(unquoted)

    parsed = urlparse(path_value)
    if parsed.scheme == "file":
        file_path = unquote(parsed.path)
        if re.match(r"^/[A-Za-z]:/", file_path):
            file_path = file_path[1:]
        return Path(file_path)
    if parsed.scheme:
        return None

    path = Path(unquoted)
    if path.is_absolute():
        return path
    return find_relative_asset(path, search_roots=search_roots or [])


def web_asset_search_roots(recipe: BookConfig) -> list[Path]:
    """Return roots searched for relative images in static web HTML."""
    roots = [
        recipe.cache_dir / "exports",
        recipe.art_dir,
        ASSETS_DIR,
        *themes.load_theme(recipe).resource_paths,
    ]
    return list(dict.fromkeys(root.resolve() for root in roots if root.exists()))


def find_relative_asset(path: Path, *, search_roots: list[Path]) -> Path | None:
    """Find a relative asset directly or by basename under known roots."""
    for root in search_roots:
        direct = root / path
        if direct.is_file():
            return direct
    if len(path.parts) != 1:
        return None
    matches: list[Path] = []
    for root in search_roots:
        matches.extend(
            candidate for candidate in root.rglob(path.name) if candidate.is_file()
        )
    if not matches:
        return None
    return sorted(matches, key=lambda candidate: candidate.as_posix())[0]


def is_non_file_reference(value: str) -> bool:
    """Return whether an HTML reference is not a local file asset."""
    lowered = value.lower()
    return (
        lowered.startswith("#")
        or lowered.startswith("http://")
        or lowered.startswith("https://")
        or lowered.startswith("data:")
        or lowered.startswith("mailto:")
        or lowered.startswith("tel:")
        or lowered.startswith("javascript:")
    )


def copy_web_image(
    source: Path,
    *,
    web_root: Path,
    copied: dict[Path, str],
) -> str:
    """Copy an image under ``assets/images`` and return its web-relative path."""
    resolved = source.resolve()
    existing = copied.get(resolved)
    if existing is not None:
        return existing

    stem = slugify(resolved.stem) or "image"
    digest = hashlib.sha256(resolved.as_posix().encode("utf-8")).hexdigest()[:10]
    filename = f"{stem}-{digest}{resolved.suffix.lower()}"
    dest = web_root / "assets" / "images" / filename
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(resolved, dest)
    relative = dest.relative_to(web_root).as_posix()
    copied[resolved] = relative
    return relative


def _parse_img_attrs(attrs_text: str) -> list[tuple[str, str | None]]:
    attrs: list[tuple[str, str | None]] = []
    for match in _HTML_ATTR_RE.finditer(attrs_text):
        name = match.group("name")
        if not name:
            continue
        value = (
            match.group("double")
            if match.group("double") is not None
            else match.group("single")
            if match.group("single") is not None
            else match.group("bare")
        )
        attrs.append((name, value))
    return attrs


def _attr_value(attrs: list[tuple[str, str | None]], name: str) -> str | None:
    lowered = name.lower()
    for attr_name, value in attrs:
        if attr_name.lower() == lowered:
            return "" if value is None else html_lib.unescape(value)
    return None


def _set_attr(attrs: list[tuple[str, str | None]], name: str, value: str) -> None:
    lowered = name.lower()
    replaced = False
    out: list[tuple[str, str | None]] = []
    for attr_name, attr_value in attrs:
        if attr_name.lower() == lowered:
            if not replaced:
                out.append((attr_name, value))
                replaced = True
            continue
        out.append((attr_name, attr_value))
    if not replaced:
        out.append((name, value))
    attrs[:] = out


def _format_img_attrs(attrs: list[tuple[str, str | None]]) -> str:
    if not attrs:
        return ""
    rendered: list[str] = []
    for name, value in attrs:
        if value is None:
            rendered.append(name)
        else:
            escaped = html_lib.escape(value, quote=True)
            rendered.append(f'{name}="{escaped}"')
    return " " + " ".join(rendered)


def _web_image_dimensions(src: str, *, web_root: Path) -> tuple[int, int] | None:
    local = _web_relative_asset(src, web_root=web_root)
    if local is None or local.suffix.lower() not in _DIMENSION_IMAGE_SUFFIXES:
        return None
    try:
        with Image.open(local) as image:
            return image.size
    except (OSError, UnidentifiedImageError):
        return None


def _web_relative_asset(src: str, *, web_root: Path) -> Path | None:
    if is_non_file_reference(src):
        return None
    parsed = urlparse(src)
    if parsed.scheme:
        return None
    value = unquote(parsed.path)
    if not value or _WINDOWS_ABSOLUTE_RE.match(value):
        return None
    path = Path(value)
    if path.is_absolute():
        return None
    root = web_root.resolve()
    candidate = (root / path).resolve()
    try:
        candidate.relative_to(root)
    except ValueError:
        return None
    return candidate if candidate.is_file() else None


def _is_decorative_web_image(
    attrs: list[tuple[str, str | None]],
    src: str | None,
) -> bool:
    classes = set((_attr_value(attrs, "class") or "").split())
    if classes & _DECORATIVE_IMAGE_CLASSES:
        return True
    stem = _asset_stem(src)
    return stem.startswith(_DECORATIVE_IMAGE_PREFIXES)


def _has_decorative_image_context(html: str, pos: int) -> bool:
    context = html[max(0, pos - 800) : pos]
    return _DECORATIVE_CONTAINER_RE.search(context) is not None


def _alt_text_from_src(src: str | None) -> str:
    stem = _asset_stem(src)
    if not stem:
        return "Illustration"
    for prefix, label in _ALT_PREFIX_LABELS:
        prefix_text = f"{prefix}-"
        if stem.startswith(prefix_text):
            subject = _humanize_stem(stem.removeprefix(prefix_text))
            return f"{label}: {subject}" if subject else label
    subject = _humanize_stem(stem)
    return f"Illustration: {subject}" if subject else "Illustration"


def _asset_stem(src: str | None) -> str:
    if not src:
        return ""
    parsed = urlparse(html_lib.unescape(src))
    stem = Path(unquote(parsed.path)).stem.lower()
    while True:
        cleaned = _HASH_SUFFIX_RE.sub("", stem)
        if cleaned == stem:
            return cleaned
        stem = cleaned


def _humanize_stem(stem: str) -> str:
    words = [word for word in re.split(r"[-_]+", stem) if word]
    return " ".join(word.capitalize() for word in words)
